-- Provenance on saved looks: who assembled it.
--
-- Owner, 2026-09-10: "The app should learn from all discussions within the
-- app, all saves, all outfits …". A look she built herself in the builder —
-- every piece chosen by hand — is the clearest statement of her taste the app
-- holds, and until now it was indistinguishable from a look Style Me
-- generated and she saved. `source` tells them apart:
--   'builder'   — assembled by hand in the builder (SilhouetteBuilder)
--   'style_me'  — generated by Style Me and saved
--   NULL        — older rows, or a path that doesn't know (treated as generated)
-- Read by features/stylist/learning.js (LOOKS SHE BUILT HERSELF, every
-- advisory surface + Style Me) and the fingerprint ([built by you] rows).
--
-- Additive-only. Safe to re-run. Until applied, saveOutfitLog strips the
-- unknown column on PGRST204 and the save lands without provenance.
--
-- APPLIED LIVE 2026-09-10.
--
-- ROLLBACK: alter table outfit_logs drop column if exists source;

alter table outfit_logs
  add column if not exists source text;

create index if not exists outfit_logs_source_idx on outfit_logs (source) where source is not null;
